apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.location }}-{{ .Release.Name }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.location }}-{{ .Release.Name }}-pod
  namespace: {{ .Values.location }}-{{ .Release.Name }}
  labels:
    app: {{ .Values.location }}-{{ .Release.Name }}-app
spec:
  containers:
    - name: {{ .Values.location }}-{{ .Release.Name }}-container
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=Response from {{ .Values.location }}"
        - "-listen=:5679"
