apiVersion: v1
kind: Namespace
metadata:
  name: multi-location
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-location-pod
  namespace: multi-location
  labels:
    app: multi-location-app
spec:
  containers:
    - name: sg-location-container
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=Response from SG"
        - "-listen=:5679"
    - name: jp-location-container
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=Response from JP"
        - "-listen=:5680"
